version: 2
project_name: dns3000

builds:
  - id: default-build
    main: ./cmd/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - android
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: android
        goarch: amd64
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}
    binary: dns3000


  - id: mips-build
    main: ./cmd/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - mips
      - mipsle
    gomips:
      - hardfloat
      - softfloat
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}
    binary: dns3000

dockers_v2:
  - images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}"
    tags:
      - "{{ .Tag }}"
      - "latest"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"


archives:
  - formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']

    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}

checksum:
  name_template: 'checksums.txt'